@startuml   
title Создание заказа доставки через агрегатор
skinparam linetype ortho
|Пользователь|
start
:Шаг 1: Открыть интерфейс создания заказа;
:Шаг 2: Ввести данные доставки;
:Шаг 3: Подтвердить создание заказа;


|Клиентское приложение|
:Шаг 4:Сформировать JSON запроса;
:Шаг 5: Отправить POST /orders;

|API Gateway|
:Шаг 6: Аутентификация пользователя;
if (Шаг 7:Пользователь авторизован?) then (Да)

else (Нет)
:Шаг 8: Вернуть 401 Unauthorized;
end
endif

|Order Service|
:Шаг 9: Получить запрос создания заказа;
:Шаг 10: Логировать входящий запрос;
:Шаг 11: Проверить структуру JSON;


if (Шаг 12: Формат запроса корректен?) then (Да)
:Шаг 13: Провести бизнес-валидацию данных;
|Order Service|
else (Нет)
|Клиентское приложение|
:Шаг 14: Вернуть 400 Invalid JSON;
:Шаг 15: Показать ошибку формата данных;
end
endif
|Order Service|
if (Шаг 16: Данные валидны?) then (Да)
|Order Service|
:Шаг 17: Создать заказ;
:Шаг 18: Сохранить заказ в БД;
:Шаг 19: Статус заказа = CREATED;
:Шаг 20: Опубликовать событие OrderCreated;

|Message Broker|
:Шаг 21: Передать событие подписчикам;

fork
  |Aggregator Service|
  :Шаг 22: Получить событие создания заказа;
  :Шаг 23: Отправить запросы службам доставки;
fork again
  |Notification Service|
  :Шаг 24: Отправить уведомление о создании заказа;
end fork

|Aggregator Service|
:Шаг 25: Ожидание ответов (таймаут 3 сек);

if (Шаг 26: Получены ответы?) then (Да)
  :Шаг 27: Нормализовать ответы API;
  :Шаг 28: Сформировать список предложений;
else (Нет)
  :Шаг 29: Вернуть ошибку "Нет доступных служб доставки";
 end
endif

else (Нет)

|Пользователь|
:Шаг 30: Вернуть 400 Bad Request;

|Клиентское приложение|
:Шаг 31: Показать ошибку данных;

|Пользователь|
:Шаг 32: Исправить данные;
note left: Пользователь исправляет данные Шаг 2\n повторяет попытку создания заказа 
detach

endif

|Клиентское приложение|
:Шаг 33: Показать варианты доставки;

|Пользователь|
:Шаг 34: Выбрать службу доставки;

|Клиентское приложение|
:Шаг 35: Отправить выбранный вариант;

|Order Service|
:Шаг 36: Обновить заказ;
:Шаг 37: Сохранить delivery_provider_id;

|Клиентское приложение|
:Шаг 38: Показать итоговую стоимость заказа;



|Пользователь|
:Шаг 39: Подготовка к оплате;
if (Шаг 40: Пользователь готов к оплате) then (Да)

:Шаг 41: Нажать "оплатить";


|Payment Service|
:Шаг 42: Инициация оплаты;

|Платежный шлюз|
:Шаг 43: Обработка платежа;

else (нет)
|Пользователь|
:Шаг 44: Отмена заказа;
end
endif

|Платежный шлюз|
if (Шаг 45: Оплата успешна?) then (Да)

|Payment Service|
:Шаг 46: Обновить статус платежа = SUCCES;

|Order Service|
:Шаг 47: Обновить статус заказа = PAID;
:Шаг 48: Опубликовать событие PaymentCompleted;

|Message Broker|
:Шаг 49: Передать событие подписчикам;

|Notification Service|
:Шаг 50: Отправить уведомление об оплате;

|Пользователь|
:Шаг 51: Получить подтверждение заказа;


stop

else (нет)
|Payment Service|
:Шаг 52: Статус платежа = FAILED;

|Order Service|
:Шаг 53: Обновить статус заказа = PAYMENT_FAILED;

|Notification Service|
:Шаг 54: Отправить уведомление об ошибке оплаты;

|Пользователь|
:Шаг 55: Показать ошибку оплаты;
if (Шаг 56: Пользователь хочет повторить попытку оплаты?) then (Да)
:Шаг 57: Выбор способа оплаты; 
note left: Пользователь переходит к шагу 39 "Подготовка к оплате"
detach
else (Нет)
   
:Шаг 58: Отмена заказа;
endif
end

@enduml




