@startuml
title Создание заказа доставки через агрегатор

|Пользователь|
start
:Открыть интерфейс создания заказа;
:Ввести данные доставки;
:Подтвердить создание заказа;

|Клиентское приложение|
:Сформировать JSON запроса;
:POST /orders;

|API Gateway|
:Аутентификация пользователя;
if (Пользователь авторизован?) then (Да)
:Передать запрос в Order Service;
else (Нет)
:Вернуть 401 Unauthorized;
stop
endif


|Order Service|
:Получить запрос создания заказа;
:Логировать входящий запрос;

:Проверить структуру JSON;

if (Формат запроса корректен?) then (Да)

:Провести бизнес-валидацию данных;
note right
Проверяется:
- user_id
- список отправлений
- адрес доставки
end note

if (Данные валидны?) then (Да)

:Создать заказ;
:Сохранить заказ в БД;
:Статус заказа = CREATED;

:Опубликовать событие OrderCreated;

|Message Broker|
:Получить событие OrderCreated;

fork

|Aggregator Service|
:Получить событие создания заказа;
:Отправить запросы службам доставки;

fork again

|Notification Service|
:Отправить уведомление
о создании заказа;

end fork


|Aggregator Service|
:Получить ответы служб доставки;

repeat
:Нормализовать ответы API;
repeat while (Ответ получен не от всех служб?) is (ожидание)


:Сформировать список предложений;

|Клиентское приложение|
:Показать варианты доставки;

|Пользователь|
:Выбрать службу доставки;

|Клиентское приложение|
:Отправить выбранный вариант;

|Order Service|
:Обновить заказ;
:Сохранить delivery_provider_id;


|Payment Service|
:Инициировать оплату;

|Платежный шлюз|
:Обработать платеж;

if (Оплата успешна?) then (Да)

|Payment Service|
:Обновить статус платежа = SUCCESS;

|Order Service|
:Обновить статус заказа = PAID;

:Опубликовать событие PaymentCompleted;

|Message Broker|
:Передать событие подписчикам;

|Notification Service|
:Отправить уведомление об оплате;

|Пользователь|
:Получить подтверждение заказа;

stop

else (Нет)

|Payment Service|
:Статус платежа = FAILED;

|Order Service|
:Обновить статус заказа = PAYMENT_FAILED;

|Notification Service|
:Отправить уведомление об ошибке оплаты;

|Пользователь|
:Получить сообщение об ошибке оплаты;

stop

endif


else (Нет)

:Вернуть 400 Bad Request;

|Клиентское приложение|
:Показать ошибку данных;

|Пользователь|
:Исправить данные заказа;

stop

endif


else (Нет)

:Вернуть 400 Invalid JSON;

|Клиентское приложение|
:Показать системную ошибку;

stop


@enduml